# Generated by Django 5.2.9 on 2025-12-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='designs.design'),
        ),
    ]
