# Generated by Django 5.2.9 on 2025-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch_url', models.URLField()),
                ('flat_url', models.URLField()),
                ('wearing_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('materials', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
