# Generated by Django 5.2.9 on 2025-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hashtags', models.TextField(blank=True, help_text='Space or comma separated hashtags')),
                ('materials', models.TextField(blank=True)),
                ('image_urls', models.JSONField(default=list, help_text='Array of image URLs')),
                ('sketch_url', models.URLField(blank=True, null=True)),
                ('tech_flat_url', models.URLField(blank=True, help_text='Technical flat design', null=True)),
                ('try_on_url', models.URLField(blank=True, help_text='Try-on/wearing image', null=True)),
                ('session_id', models.CharField(blank=True, help_text='Lambda generation session ID', max_length=100, null=True)),
                ('funding_progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Funding progress (0.0-1.0)', max_digits=3)),
                ('funding_amount', models.CharField(blank=True, default='₩0', help_text='Current funding amount', max_length=50)),
                ('funding_goal', models.CharField(blank=True, default='₩0', help_text='Funding goal amount', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
