# Generated by Django 5.2.9 on 2025-12-10 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['user_id'], name='designs_des_user_id_84d3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['-created_at'], name='designs_des_created_e3335c_idx'),
        ),
    ]
