# Generated by Django 5.2.9 on 2025-12-10 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0002_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='designs.design'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user_id'], name='social_book_user_id_7d6158_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['-created_at'], name='social_book_created_893865_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('design', 'user')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower_id'], name='social_foll_followe_9bcca8_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followee_id'], name='social_foll_followe_cc0c55_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='no_self_follow'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['design', 'user'], name='social_like_design__4daf8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('design', 'user')},
        ),
    ]
